Create PermissionGuardType + allow embeds as custom reply
oceanroleplay/discord.ts pull request #645
Opened 2022-04-20 20:27 UTC by bycop

**Please describe the changes this PR makes and why it should be merged:**

Simple modification who replace the content (string) option by PermissionGuardOption to control ephemeral state and choose between string or embed for reply content.

## Package
@discordx/utilities

2022-04-20 20:29 UTC, VictoriqueMoe commented
Please add documentation to `\packages\utilities\README.md`

2022-04-20 20:32 UTC, bycop commented
> Please add documentation to `\packages\utilities\README.md`

Done !

2022-04-20 20:45 UTC, VictoriqueMoe requested changes
Please see comments

2022-04-20 20:45 UTC, VictoriqueMoe commented on packages/utilities/src/guards/PermissionGuard/PermissionGuard.ts
> +    if (options.content instanceof MessageEmbed)
2 things:

1. please use brackets, please run the linter,
2. `else` is not necessary

```ts
if (options.content instanceof MessageEmbed){
	return post(arg, { embeds: [options.content], ephemeral: options.ephemeral ? true : false });
}
  
return post(arg, { content: options.content, ephemeral: options.ephemeral ? true : false });
```
is enough

2022-04-20 20:45 UTC, VictoriqueMoe commented on packages/utilities/src/guards/PermissionGuard/PermissionGuard.ts
> +    msg: object
Do not use `object` Resolve this to a type

2022-04-20 20:45 UTC, VictoriqueMoe commented on packages/utilities/src/guards/PermissionGuard/PermissionGuard.ts
> +    if (options.content instanceof MessageEmbed)
Please can this actually be refactored? 

```ts
const postOptions = {ephemeral: options.ephemeral ? true : false };
if(options.content instanceof MessageEmbed){
   postOptions["embeds"] = [options.content];
}else{
    postOptions["embeds"] = options.content;
}
return post(arg, postOptions);
```

2022-04-20 20:45 UTC, VictoriqueMoe commented on packages/utilities/README.md
> +    PermissionGuard(["BAN_MEMBERS"], PermissionGuards.genEmbed())
are you sure this is correct?

should it not be:

```ts
@PermissionGuard(["BAN_MEMBERS"], {
  content: PermissionGuards.genEmbed()
})
```
?

2022-04-20 21:20 UTC, VictoriqueMoe commented
`\examples\guards\commands\PermissionGuards.ts` does not compile at all, please update this file and run it through tsc

2022-04-20 22:20 UTC, VictoriqueMoe submitted a review, later dismissed
All comments are addressed and i am happy with the code

2022-04-20 23:22 UTC, oceanroleplay commented on packages/utilities/README.md
> +The guard can take an array of permissions or an async resolver to the permission array and a PermissionGuardOptions object with `content` and `ephemeral` values.
```suggestion
Permission guards can take an array of permissions or an async resolver to the permission array, as well as a PermissionGuardOptions object that contains `content` and `ephemeral` values.
```

2022-04-20 23:25 UTC, oceanroleplay commented on packages/utilities/src/guards/PermissionGuard/PermissionGuard.ts
> + * @param options - Options for the guard reply. Available options are: `content` (string or MessageEmbed) and `ephemeral` (boolean) defaults to `content`: "No permissions" and `ephemeral`: false
instead of ``No permissions`` print the required permissions. something like

``you need x, x, x permission for this command``

2022-04-21 06:43 UTC, oceanroleplay commented
see https://github.com/oceanroleplay/discord.ts/commit/07043351fee7f06b85b9a51da23257ed215bfbe9

2022-04-21 07:29 UTC, oceanroleplay commented
also see https://github.com/oceanroleplay/discord.ts/commit/641fba58183f6d84e94878f5e44980a899f3cb04

and this changes are untested

cc @VictoriqueMoe

2022-04-21 09:24 UTC, VictoriqueMoe commented
> also see [641fba5](https://github.com/oceanroleplay/discord.ts/commit/641fba58183f6d84e94878f5e44980a899f3cb04)
> 
> and this changes are untested
> 
> cc @VictoriqueMoe

Okay. I thought you wanted to avoid:
```ts
MessageOptions & {
  ephemeral?: boolean;
};
```
due to using only djs types? but i am happy with this anyway

2022-04-21 09:25 UTC, VictoriqueMoe commented
Make sure you update the examples and docs

2022-04-21 09:25 UTC, oceanroleplay commented
> 

I did but ``untested`` updates. so would be good if you test everything.

2022-04-21 09:58 UTC, VictoriqueMoe commented
> 

I would get @bycop to test, as he is the one using this guard

2022-04-21 20:39 UTC, bycop commented
I've tested and it's ok for me

2022-04-22 02:06 UTC, closed without merging